## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adam, RMSprop, Adagrad, Adadelta, Adamax, Nadam
from tensorflow.keras.callbacks import EarlyStopping
import re
import openpyxl
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 120
application_types_to_replace = list(application_counts[application_counts <= cutoff_value].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
filtered_classification_counts = classification_counts[classification_counts > 1]
print(filtered_classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 100
classification_counts = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = list(classification_counts[classification_counts <= cutoff_value].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_converted = pd.get_dummies(application_df, columns=['APPLICATION_TYPE', 'CLASSIFICATION', 'AFFILIATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'], drop_first=True)
application_df_converted

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
4,1,142590,1,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34295,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34296,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [10]:
# Create the target array y by extracting the 'IS_SUCCESSFUL' column
y = application_df_converted['IS_SUCCESSFUL'].values
X = application_df_converted.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

# Define the number of neurons for the first hidden layer
hidden_nodes_layer1 = 64

# Define the number of neurons for the second hidden layer
hidden_nodes_layer2 = 32

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=input_features, activation='relu'))

# Second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                2816

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 4,929
Trainable params: 4,929
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Define a list of optimizers
optimizers = [SGD(), Adam(), RMSprop(), Adagrad(), Adadelta(), Adamax(), Nadam()]

In [14]:
# Create DataFrame to store the results
results_df = pd.DataFrame(columns=['optimizer', 'train_loss', 'train_accuracy', 'val_loss', 'val_accuracy'])

>The following code adds an EarlyStopping callback with a patience of 10 epochs, meaning that the training will stop if the validation loss doesn't improve for 10 consecutive epochs. This can significantly speed up the training process without compromising the integrity of the model.

In [15]:
num_epochs = 100
batch_size = 32

# Define early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Loop through the optimizers
for optimizer in optimizers:
    # Create and compile the model with the current optimizer
    nn.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    # Train the model with early stopping
    history = nn.fit(
        X_train_scaled,
        y_train,
        epochs=num_epochs,
        batch_size=batch_size,
        verbose=0,
        validation_split=0.2,
        callbacks=[early_stopping]
    )

    # Extract optimizer name using regex
    optimizer_name = re.search(r"optimizer_v2\.(.+?)\.", str(optimizer)).group(1)
    
    # Save the results to the DataFrame
    results_df = results_df.append({
        'optimizer': optimizer_name,
        'train_loss': history.history['loss'][-1],
        'train_accuracy': history.history['accuracy'][-1],
        'val_loss': history.history['val_loss'][-1],
        'val_accuracy': history.history['val_accuracy'][-1]
    }, ignore_index=True)

In [16]:
# Save the DataFrame to a CSV file
results_df.to_csv('optimizer_results.csv',
                  index=False,
                  header=True,
                  float_format='%.2f')

In [17]:
# Print the results
print(results_df)

          optimizer  train_loss  train_accuracy  val_loss  val_accuracy
0  gradient_descent    0.539459        0.737548  0.559243      0.718950
1              adam    0.535677        0.739686  0.560681      0.723421
2           rmsprop    0.543106        0.737451  0.565158      0.725559
3           adagrad    0.531463        0.742359  0.556789      0.726725
4          adadelta    0.531420        0.742407  0.556853      0.726725
5            adamax    0.530740        0.743136  0.557415      0.718562
6             nadam    0.534056        0.742359  0.561748      0.721283

In [18]:
# Play a sound to let you know its done 
import winsound
duration = 8000    # milliseconds
freq = 440  # Hz
winsound.Beep(freq, duration)

In [19]:
# Create a new Excel workbook and add a worksheet
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Optimizer Results"

# Write the DataFrame to the worksheet
for r in dataframe_to_rows(results_df, index=False, header=True):
    ws.append(r)

# Apply formatting to the header row
for cell in ws["1:1"]:
    cell.font = Font(bold=True)
    cell.alignment = Alignment(horizontal="center", vertical="center")
    cell.fill = PatternFill(start_color="FFC0CB", end_color="FFC0CB", fill_type="solid")
    cell.border = Border(left=Side(style='thin'), 
                         right=Side(style='thin'), 
                         top=Side(style='thin'), 
                         bottom=Side(style='thin'))

# Apply formatting to the data cells
for row in ws.iter_rows(min_row=2):
    for cell in row:
        cell.number_format = '0.00'
        cell.alignment = Alignment(horizontal="right", vertical="center")
        cell.border = Border(left=Side(style='thin'), 
                             right=Side(style='thin'), 
                             top=Side(style='thin'), 
                             bottom=Side(style='thin'))

# Adjust column widths
for column_cells in ws.columns:
    length = max(len(str(cell.value)) for cell in column_cells)
    ws.column_dimensions[column_cells[0].column_letter].width = length + 2

# Save the workbook to an Excel file
wb.save('optimizer_results.xlsx')

In [20]:
sorted_results = results_df.sort_values(by='val_accuracy', ascending=False)
sorted_results

          optimizer  train_loss  train_accuracy  val_loss  val_accuracy
3           adagrad    0.531463        0.742359  0.556789      0.726725
4          adadelta    0.531420        0.742407  0.556853      0.726725
2           rmsprop    0.543106        0.737451  0.565158      0.725559
1              adam    0.535677        0.739686  0.560681      0.723421
6             nadam    0.534056        0.742359  0.561748      0.721283
0  gradient_descent    0.539459        0.737548  0.559243      0.718950
5            adamax    0.530740        0.743136  0.557415      0.718562

In [21]:
# Get the optimizer of the best-performing model
best_optimizer = sorted_results.iloc[0]['optimizer']
best_optimizer

'adagrad'

In [22]:
# Define the best model using the best optimizer
best_model = Sequential()
best_model.add(Dense(units=16, activation='relu', input_dim=X_train.shape[1]))
best_model.add(Dense(units=8, activation='relu'))
best_model.add(Dense(units=1, activation='sigmoid'))

In [23]:
optimizer_dict = {
    "adam": Adam,
    "sgd": SGD,
    "rmsprop": RMSprop,
    "adadelta": Adadelta,
    "adagrad": Adagrad,
    "adamax": Adamax,
    "nadam": Nadam
}

In [24]:
best_optimizer_string = results_df.loc[results_df['val_accuracy'].idxmax(), 'optimizer']
best_optimizer_string

'adagrad'

In [25]:
best_optimizer_instance = optimizer_dict[best_optimizer_string]()

In [26]:
# Compile the best model
best_model.compile(optimizer=best_optimizer_instance, loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
# Train the best model
# early_stopping = EarlyStopping(monitor='loss', patience=10, restore_best_weights=True)
# best_model.fit(X_train_scaled, y_train, epochs=100, verbose=1, callbacks=[early_stopping])
best_model.fit(X_train_scaled, y_train, epochs=100, verbose=1)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.7148 - accuracy: 0.5112
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6960 - accuracy: 0.5412
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6860 - accuracy: 0.5637
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6793 - accuracy: 0.5830
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6742 - accuracy: 0.6017
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6701 - accuracy: 0.6069
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6667 - accuracy: 0.6076
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6637 - accuracy: 0.6100
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6610 - accuracy: 0.6309
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6585 - accuracy: 0.6400
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6562 - accuracy: 0.6457
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6541 - accuracy: 0.6457
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6522 - accuracy: 0.6455
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6502 - accuracy: 0.6455
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6483 - accuracy: 0.6527
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6464 - accuracy: 0.6621
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6447 - accuracy: 0.6633
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6429 - accuracy: 0.6632
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6413 - accuracy: 0.6738
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6397 - accuracy: 0.6893
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6381 - accuracy: 0.6901
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6364 - accuracy: 0.6937
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6347 - accuracy: 0.6968
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6330 - accuracy: 0.6971
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6312 - accuracy: 0.6975
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6295 - accuracy: 0.6974
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6279 - accuracy: 0.6974
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6263 - accuracy: 0.6976
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6249 - accuracy: 0.6976
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6235 - accuracy: 0.6978
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6221 - accuracy: 0.6978
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6209 - accuracy: 0.7003
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6197 - accuracy: 0.7030
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6184 - accuracy: 0.7041
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6171 - accuracy: 0.7039
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6159 - accuracy: 0.7044
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6147 - accuracy: 0.7059
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6136 - accuracy: 0.7066
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6125 - accuracy: 0.7066
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6114 - accuracy: 0.7069
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6104 - accuracy: 0.7072
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6094 - accuracy: 0.7074
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6085 - accuracy: 0.7077
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6075 - accuracy: 0.7077
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6066 - accuracy: 0.7078
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6058 - accuracy: 0.7079
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6049 - accuracy: 0.7086
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6041 - accuracy: 0.7098
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6033 - accuracy: 0.7100
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6025 - accuracy: 0.7098
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6016 - accuracy: 0.7102
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6006 - accuracy: 0.7107
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5996 - accuracy: 0.7107
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5986 - accuracy: 0.7109
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5976 - accuracy: 0.7119
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5967 - accuracy: 0.7119
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5957 - accuracy: 0.7121
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5948 - accuracy: 0.7123
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5939 - accuracy: 0.7124
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5930 - accuracy: 0.7124
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5921 - accuracy: 0.7124
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5913 - accuracy: 0.7131
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5905 - accuracy: 0.7139
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5898 - accuracy: 0.7156
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5891 - accuracy: 0.7160
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5884 - accuracy: 0.7179
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5877 - accuracy: 0.7212
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5870 - accuracy: 0.7214
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5864 - accuracy: 0.7219
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5856 - accuracy: 0.7220
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5848 - accuracy: 0.7220
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5841 - accuracy: 0.7220
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5834 - accuracy: 0.7223
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5828 - accuracy: 0.7224
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5822 - accuracy: 0.7236
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5816 - accuracy: 0.7236
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5810 - accuracy: 0.7249
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5805 - accuracy: 0.7251
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5800 - accuracy: 0.7252
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5795 - accuracy: 0.7252
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5790 - accuracy: 0.7253
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5786 - accuracy: 0.7254
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5781 - accuracy: 0.7256
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5777 - accuracy: 0.7257
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5773 - accuracy: 0.7259
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5769 - accuracy: 0.7262
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5766 - accuracy: 0.7263
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5762 - accuracy: 0.7264
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5758 - accuracy: 0.7264
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5755 - accuracy: 0.7265
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5751 - accuracy: 0.7265
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5748 - accuracy: 0.7265
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5745 - accuracy: 0.7265
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5741 - accuracy: 0.7267
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5739 - accuracy: 0.7268
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5736 - accuracy: 0.7268
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5733 - accuracy: 0.7266
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5730 - accuracy: 0.7266
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5728 - accuracy: 0.7266
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5725 - accuracy: 0.7266

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5603 - accuracy: 0.7244 - 550ms/epoch - 2ms/step
Loss: 0.5602618455886841, Accuracy: 0.7244315147399902

In [29]:
# Export the best model to an HDF5 file
best_model.save('AlphabetSoupCharity.h5')